-- Cherepovets89 / GOV site: базовая схема для нового Supabase-проекта.
-- Выполнять в Supabase -> SQL Editor -> New query.
-- Этот SQL создаёт таблицы сайта, VK-привязок и Vercel VK-бота.
-- Auth-пользователи создаются через Supabase Auth при регистрации на сайте; пароли старых пользователей SQL не переносит.

create extension if not exists pgcrypto;

-- Общий trigger для updated_at.
create or replace function public.ch89_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Основная таблица: отчёты, роли, настройки, служебные записи, баллы.
create table if not exists public.reports (
  id text primary key,
  email text not null default '',
  link text not null default '',
  date text not null default '',
  status text not null default '',
  xp numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists reports_email_idx on public.reports (email);
create index if not exists reports_link_idx on public.reports (link);
create index if not exists reports_status_idx on public.reports (status);
create index if not exists reports_email_status_idx on public.reports (email, status);
create index if not exists reports_email_link_idx on public.reports (email, link);
create index if not exists reports_xp_idx on public.reports (xp);

drop trigger if exists ch89_reports_touch_updated_at on public.reports;
create trigger ch89_reports_touch_updated_at
before update on public.reports
for each row execute function public.ch89_touch_updated_at();

-- Профили и статистика пользователей сайта.
create table if not exists public.user_stats (
  user_id text primary key,
  email text not null default '',
  nickname text not null default '',
  mod_correct integer not null default 0,
  sup_correct integer not null default 0,
  shop_spent numeric not null default 0,
  ap_spent numeric not null default 0,
  xp numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists user_stats_email_idx on public.user_stats (email);
create index if not exists user_stats_nickname_idx on public.user_stats (nickname);
create index if not exists user_stats_shop_spent_idx on public.user_stats (shop_spent);

drop trigger if exists ch89_user_stats_touch_updated_at on public.user_stats;
create trigger ch89_user_stats_touch_updated_at
before update on public.user_stats
for each row execute function public.ch89_touch_updated_at();

-- Логи магазина/выдачи товаров.
create table if not exists public.admin_logs (
  id bigint generated by default as identity primary key,
  user_email text not null default '',
  nickname text not null default '',
  item_name text not null default '',
  cost numeric not null default 0,
  type text not null default '',
  status text not null default 'Ожидает выдачи',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists admin_logs_user_email_idx on public.admin_logs (user_email);
create index if not exists admin_logs_type_idx on public.admin_logs (type);
create index if not exists admin_logs_status_idx on public.admin_logs (status);
create index if not exists admin_logs_created_at_idx on public.admin_logs (created_at desc);

drop trigger if exists ch89_admin_logs_touch_updated_at on public.admin_logs;
create trigger ch89_admin_logs_touch_updated_at
before update on public.admin_logs
for each row execute function public.ch89_touch_updated_at();

-- Привязка VK ID к аккаунту сайта.
create table if not exists public.vk_links (
  vk_user_id text primary key,
  site_user_id text not null,
  email text not null default '',
  nickname text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists vk_links_site_user_id_key on public.vk_links (site_user_id);
create index if not exists vk_links_email_idx on public.vk_links (email);

drop trigger if exists ch89_vk_links_touch_updated_at on public.vk_links;
create trigger ch89_vk_links_touch_updated_at
before update on public.vk_links
for each row execute function public.ch89_touch_updated_at();

-- Сессии формы /отчет для serverless-бота на Vercel.
create table if not exists public.vk_report_sessions (
  session_key text primary key,
  vk_user_id text not null,
  peer_id text not null,
  step text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists vk_report_sessions_vk_user_id_idx on public.vk_report_sessions (vk_user_id);
create index if not exists vk_report_sessions_updated_at_idx on public.vk_report_sessions (updated_at);

drop trigger if exists ch89_vk_report_sessions_touch_updated_at on public.vk_report_sessions;
create trigger ch89_vk_report_sessions_touch_updated_at
before update on public.vk_report_sessions
for each row execute function public.ch89_touch_updated_at();

-- Права доступа.
-- Для совместимости со старым фронтендом основные таблицы открыты для клиента сайта.
-- Ограничение прав в этом проекте в основном сделано на уровне UI/логики сайта.
alter table public.reports disable row level security;
alter table public.user_stats disable row level security;
alter table public.admin_logs disable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on public.reports to anon, authenticated, service_role;
grant select, insert, update, delete on public.user_stats to anon, authenticated, service_role;
grant select, insert, update, delete on public.admin_logs to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;

-- vk_links доступна пользователю только для своей привязки. Бот с service_role обходит RLS.
alter table public.vk_links enable row level security;

drop policy if exists vk_links_select_own on public.vk_links;
create policy vk_links_select_own
on public.vk_links
for select
to authenticated
using (auth.uid()::text = site_user_id);

drop policy if exists vk_links_insert_own on public.vk_links;
create policy vk_links_insert_own
on public.vk_links
for insert
to authenticated
with check (auth.uid()::text = site_user_id);

drop policy if exists vk_links_update_own on public.vk_links;
create policy vk_links_update_own
on public.vk_links
for update
to authenticated
using (auth.uid()::text = site_user_id)
with check (auth.uid()::text = site_user_id);

drop policy if exists vk_links_delete_own on public.vk_links;
create policy vk_links_delete_own
on public.vk_links
for delete
to authenticated
using (auth.uid()::text = site_user_id);

grant select, insert, update, delete on public.vk_links to authenticated, service_role;

-- vk_report_sessions должна использоваться только ботом через service_role.
alter table public.vk_report_sessions enable row level security;
grant select, insert, update, delete on public.vk_report_sessions to service_role;

-- Чтобы PostgREST сразу увидел новые таблицы.
notify pgrst, 'reload schema';
